### ISSUE TITLE
Add @turf/line-intersect to docs

### ISSUE THREAD

**Issue by rowanwins** [Turfjs/turf-www#101]
Add the @turf/line-intersect to docs
See https://github.com/Turfjs/turf/issues/586

**Comment by DenisCarriere** [comment]
👍 I always forget adding the new modules to the docs

**Comment by rowanwins** [comment]
Just looking at the jsdocs for this @DenisCarriere - the module is called `lineIntersect` but it accepts lines or polygons. We already have the the `intersect` module which does polys. Just trying to work out if we need to rationalise them or change the name of `lineIntersect`?

**Comment by DenisCarriere** [comment]
1. Well Polygons are also a collection of lines (I just made it easier to deflate polygons into lines).
2. `@turf/intersect` has `jsts` and should be entirely removed (Turf 4.0 should not have any `jsts`)
3. `@turf/line-intersects` returns a `Feature<Point>` where `@turf/intersect` returns **RANDOM**.

It's hard to have a function `intersect` when it could mean a thousand different things.

Ideally we also need a module that `intersect` returns true/false (very rapidly) mentioned here https://github.com/Turfjs/turf/issues/203.

**Comment by rowanwins** [comment]
yeah ok, so I'll update the docs with what we've got at the moment and as you say hopefully introducing the examples will help again.

**Comment by DenisCarriere** [comment]
👍 Added to www
