### ISSUE TITLE
AddToMap JSDocs linting warning

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf-www#106]
So far the automated TurfJS map example looks great!

At the moment, it works by adding `@addToMap` to the JSDocs.

However, we're going to have linting warnings with `DocumentionJS` because of the unknown `@addToMap` tag.

**Solution (Options)**

- Use `//=` feature tags to display map
- Ignore documetation warnings

```bash
> turf-www@1.0.0 lintAPI /Users/mac/Github/turf-www-main
> documentation lint turf/packages/turf-*/index.js

/Users/mac/Github/turf-www-main/turf/packages/turf-along/index.js
       14:1  warning  unknown tag @addToMap

/Users/mac/Github/turf-www-main/turf/packages/turf-mask/index.js
       14:1  warning  unknown tag @addToMap

⚠ 2 warnings
```

**AddToMap JSDocs**

```javascript
/**
 * ...
 * @addToMap masked
 * @example
 * var polygon = {
 *   "type": "Feature",
 *   "properties": {},
 *   "geometry": {
 *     "type": "Polygon",
 *     "coordinates": [[[112, -21], [116, -36], [146, -39], [153, -24], [133, -10], [112, -21]]]
 *   }
 * }
 * var mask = {
 *   "type": "Feature",
 *   "properties": {},
 *   "geometry": {
 *     "type": "Polygon",
 *     "coordinates": [[[90, -55], [170, -55], [170, 10], [90, 10], [90, -55]]]
 *   }
 * }
 * var masked = turf.mask(polygon, mask);
 * //=masked
 */
```

[**Mask**](http://localhost:9080/docs/#mask)

![image](https://cloud.githubusercontent.com/assets/550895/23840831/eb23756c-077e-11e7-81c2-6bef90fb490b.png)

CC: @tmcw @rowanwins

**Comment by rowanwins** [comment]
Thanks for spotting this @DenisCarriere 

`jsdoc` supports custom tags, apparently this can be configured via a config file, [this link](http://stackoverflow.com/questions/40263846/create-custom-tags-with-jsdoc) provides a bit of an example as to how it's done.

Im not sure how this interacts with documentation.js which is where we might need the help of @tmcw . We currently don't seem to have any sort of jsdoc config although I think our [index.js](https://github.com/Turfjs/turf-www/blob/gh-pages/template/turf_2017/index.js) is our documentation.js config, I'm not sure how these interact...

**Comment by DenisCarriere** [comment]
Doesn't seem like there's going to be a way (for now) to remove that `documentation lint` warning message.

Looks like `flatteners` doesn't have a way to be expanded: https://github.com/documentationjs/documentation/blob/master/lib/parse.js#L8-L402

If if we change the JSDocs config or ESLint, it doesn't read it...

We can keep this issue open until there's a fix.

**Comment by rowanwins** [comment]
Someone has asked the same question about [custom tags in the documentation.js repo](https://github.com/documentationjs/documentation/issues/683) so just pinning it here for reference

**Comment by tmcw** [comment]
The intent here is to show the example map, but not in context with its code around it, like in rpl? In that case, could we instead just have the examples always output the same variable name rather than using a custom JSDoc tag to specify it?

**Comment by rowanwins** [comment]
Correct @tmcw , the aim is to just to get a map going. The downside I see with the one variable approach (and why I went the custom tag route) is that on some maps you want to show both the input and output, in this case you then need to combine the input and output into one featurecollection, which in my opinion reduces the clarity in the docs, [kinks](http://turfjs.org/docs/#kinks) is a good example of where this happens.

I guess with every approach there will be tradeoffs, it's just a matter as to which is the best one to make :)

**Comment by tmcw** [comment]
say the output is `output`, you could make it an Array, or even allow it to be an array for multi-map examples or an object for single maps, since GeoJSON objects are always objects and there wouldn't be any ambiguity.

**Comment by rowanwins** [comment]
Ok so I guess we're going back to how it kind of was.... I'll rejig what I've done and see if I can get it going without the custom tag.

**Comment by DenisCarriere** [comment]
I think we all agree that the `@addToMap` custom tag was simply a prototype to get a map working.

I still personally vote we should be using the `//=` in the standard `@example` description, however... having a few map "trial" examples is good to do first instead of applying this logic to the entire repo.

We've only done a few `addToMap` examples and out of those few I'd say 80% of them we modified heavily the JSDocs example.

This is a big working progress! But the results are awesome!! I really like the new maps that are being auto-generated from the JSDocs, this is definitely heading in the right direction. 👍

**Comment by rowanwins** [comment]
Ok so I before I implement this incorrectly again... :)

The proposal as I understand it is is that we look in the `@example` tag, 
- @tmcw suggested this could be done by looking for a specific variable 
   (eg `var output = [inputPoints, outputFC]`)
- @DenisCarriere suggested we could use the `//=result`

While Im sure either is achievable my concerns are
- making sure that the code examples that are shown on the site are readable and logical to people
- can handle the variability in what we'll want to show on maps
  - in some cases we'll only show the output
  - in some cases we'll show input and output
  - in some cases the outputs are't geographic and we'll need to think how we want to handle that

Im less inclined to use the `//=result` because it seems to me that that should reflect the output of the turf method so to start combing it with inputs seems a bit misleading. 

So I'd probably lean towards the `var output = [...]` approach. However on top of that I'd probably then attempt to mask them out of the actual code example that gets printed just to reduce confusion for people reading the docs.

So for example turf/collect would look something like this in the actual module
````
 * @example
 * var poly1 = turf.polygon([[[0,0],[10,0],[10,10],[0,10],[0,0]]]);
 * var poly2 = turf.polygon([[[10,0],[20,10],[20,20],[20,0],[10,0]]]);
 * var polyFC = turf.featureCollection([poly1, poly2]);
 * var pt1 = turf.point([5,5], {population: 200});
 * var pt2 = turf.point([1,3], {population: 600});
 * var pt3 = turf.point([14,2], {population: 100});
 * var pt4 = turf.point([13,1], {population: 200});
 * var pt5 = turf.point([19,7], {population: 300});
 * var ptFC = turf.featureCollection([pt1, pt2, pt3, pt4, pt5]);
 * var collected = turf.collect(polyFC, ptFC, 'population', 'values');
 * //=collected
 * var output = [ptFC, collected]; 
 */
````
and then on the docs page it would not display the `var output = [ptFC, collected]`

Does that sound reasonable or am I overthinking this all?

**Comment by DenisCarriere** [comment]
Could we use a variable name that explicitly defines what it's going to do such as `addToMap` instead of using `output`.

```javascript
var addToMap = [ptFC, collected];
```

Things to consider while implementing this:
- Handling both FeatureCollections & Features within the Array.
- Map Zoom to Extent `fitBounds()` should be based on the maximum extent of all features (not only the first or last Feature)

Also @morganherlocker brought up a very valid point about not overloading the browser page with the map examples. For a better mobile experience, loading multiple maps all at once might be pretty demanding for bandwidth, it might be better only to include the maps upon users request (add a `+ Expand Map` button) instead of loading ALL the maps for the entire API page.

At the moment we only have ~5 maps, but imagine if we had 50+ maps all being loaded simultaneously. 

@rowanwins 👍 you're on the right track.

**Comment by rowanwins** [comment]
Ok so an update on this at long last :)

So I've moved things back into the `@example` - what I've done is added a  `//addToMap` comment

````
 * @example
 * var line = {
 *   "type": "Feature",
 *   "geometry": {
 *     "type": "LineString",
 *     "coordinates": [
 *       [-77.031669, 38.878605],
 *       [-77.029609, 38.881946],
 *       [-77.020339, 38.884084],
 *       [-77.025661, 38.885821],
 *       [-77.021884, 38.889563],
 *       [-77.019824, 38.892368]
 *     ]
 *   }
 * };
 *
 * var along = turf.along(line, 1, 'miles');
 * //addToMap
 * var addToMap = [along, line]
````

Anything after the ` //addToMap` comment is removed from the code example in the module which means they can be a bit more concise by moving things like the simple-style stuff to down below this comment.  In the module then author then specifies an `addToMap` array which is the features that will get added to the map.

The other major change is that on the front end there is now only 1 map, as the user scrolls up and down the page the map moves and updates according to the example. This appears to be working pretty well at the moment, you barely notice the div moving around.

So how does all that sound @DenisCarriere ? Happy to put through a pull request showing the approach.

![](https://www.dropbox.com/s/odga5dt2en8tuca/latestExample.jpeg?dl=1)

**Comment by DenisCarriere** [comment]
That sounds pretty good! I'd like to see the single div map solution, I think that's a pretty good approach for low bandwidth devices.

**Comment by rowanwins** [comment]
Gday @DenisCarriere 

You can see a demo of my latest version of the docs here
https://rowanwins.github.io/turf-www/docs/
Scroll down the page and a map will appear for the `along` module and as you keep you scrolling maps will appear for additional modules, I've just done the first half dozen or so modules on the page for demo purposes. 

I've also wired it up to the sidebar links so if you click those the maps will also appear.

It still needs a bit of hardening up but if you're happy with the approach I'll get on with that.

Cheers
R

**Comment by DenisCarriere** [comment]
👍 That works! I've only been able to see two maps in your demo example, however from that it seems to work, the map only loads when you scroll down to the page.

Here's the Google Chrome network activity graph of the map tiles being loaded (timeline is separated == good 👍 )

![image](https://cloud.githubusercontent.com/assets/550895/24686472/2706b85e-1982-11e7-8320-9f0c3dc80660.png)

Another error came up from `@turf/unkink-polygon`, would need to fix that since it breaks the demo page.

```
Uncaught TypeError: process.hrtime is not a function
    at module.exports (turf.js:12449)
    at turf.js:12138
    at featureEach (turf.js:1337)
    at turf.js:12137
    at featureEach (turf.js:1337)
    at Object.module.exports [as unkinkPolygon] (turf.js:12131)
    at rowanwins.github.io/:6807
```
https://github.com/mclaeysb/simplepolygon/search?utf8=%E2%9C%93&q=process.hrtime&type=

**Comment by rowanwins** [comment]
yeah I saw that error. It looks like someone has created a [browser shim](https://www.npmjs.com/package/browser-process-hrtime) for the process.hr so we can probably put a pull request in for simplepolygon

Will work on hardening up the moving map approach and fingers crossed it might be up and running by the weekend

**Comment by DenisCarriere** [comment]
The `process.hrtime` should be entirely removed... it's only used for debugging (could use [`debug`](https://www.npmjs.com/package/debug) for that).

Also noticed this:

```javascript
Number.prototype.modulo = function(n) {
  return ((this%n)+n)%n;
}
```

This `simplepolygon` library needs a clean up.

**Comment by DenisCarriere** [comment]
Pretty confident that this is solved using @rowanwins's approach with `//addToMap` (easy implementation to optionally include a map to the Turf-www docs).
