### ISSUE TITLE
Group Coordinates mutation modules

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf-www#112]
List of Turf modules that mutates coordinates can be grouped together:

- [`@turf/truncate`](https://github.com/Turfjs/turf/tree/master/packages/turf-truncate)
- [`@turf/flip`](https://github.com/Turfjs/turf/tree/master/packages/turf-flip)

@rowanwins Can you think of any other ones?

**Comment by rowanwins** [comment]
Docs updated with coordinate mutation group

**Comment by DenisCarriere** [comment]
👍
