### ISSUE TITLE
Publishing updates to TurfJS website

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf-www#113]
@stebogit I recall you asking about how to publish to the TurfJS website, if you check out [`CONTRIBUTING.md`](https://github.com/Turfjs/turf-www/blob/gh-pages/CONTRIBUTING.md), there should be enough information there to do some updates.

@rowanwins has been doing the lastest updates, it's not 100% automated, but it's relatively an easy process to do.

Extra documentation to publish updates would always be beneficial, but if you need any extra help with it, let me know.

**Comment by stebogit** [comment]
@DenisCarriere @rowanwins 
I followed the instructions of `CONTRIBUTING.md` for deploying, but I got an error.
So I changed a couple of lines in `template/turf_2017/index.js` (based on `documentation.js`[`#810`](https://github.com/documentationjs/documentation/issues/810)) :
```js
-  createLinkerStack = require('documentation').util.createLinkerStack,
+  linkerStack = require('documentation').util.LinkerStack,

```
However, I'm now getting this error when trying to deploy, which I'm not able to fix:
![screen shot 2017-07-11 at 12 18 10 am](https://user-images.githubusercontent.com/12717225/28056030-4d7d2190-65d0-11e7-84ce-e497d3f614e5.png)
It seems to be related to `documentation.js`[`#132`](https://github.com/documentationjs/documentation/issues/132), but I don't know how to use Tom's suggestion

BTW may I have writing permission to this repo as well, so I can commit my branch/changes?

**Comment by rowanwins** [comment]
Hi @stebogit 

Yeah I ran into some issues last time I tried to update the docs.  What version of `documentation.js` are you running? I think I may have reverted back to `4.0.0-beta.18` to fix things, we may need to update that in the package.json, or work out how to update the whole project to support the new config bits and pieces....

**Comment by stebogit** [comment]
@rowanwins I'm using version `4.0.0-beta.18`, which is what is set in the repo and is currently the [latest one](https://github.com/documentationjs/documentation/releases).
It seems the `buildAPI` script is not allowed to 'do stuff' in the docs folder.

BTW thanks @DenisCarriere for the permission, I just pushed my branch so you can take a look, I didn't really do anything special.

**Comment by DenisCarriere** [comment]
👍 @rowanwins has been the lead man for the past few `turf-www` updates, I haven't dived into the **www** too much.

**Comment by rowanwins** [comment]
Hey @stebogit 

Just double check in your node_modules folder that you've got the right version installed. 

Our package says `^4.0.0-beta.18` so you might have something higher as there are newer versions published on [npm](https://www.npmjs.com/package/documentation). We should adjust our package.json to nail down the version - or update our docs workflow to match the latest stuff (although last time I looked this was fiddly for some reason I now forget :)  )

**Comment by stebogit** [comment]
👍  I now have v. `4.0.0-beta.18` installed. I changed back the code to 
```js
createLinkerStack = require('documentation').util.createLinkerStack,
```
in `index.js` and updated the local Turf repo.

Tried to run, this time got this error:

![screen shot 2017-07-22 at 12 39 09 am](https://user-images.githubusercontent.com/12717225/28489330-88bdaa64-6e76-11e7-99c6-d3aefe1ee2d4.png)

**Comment by rowanwins** [comment]
ah yes I remember, there are some modules where the //addToMap tags aren't quite right
The var addToMap needs to be right after the tag
`````
 * //addToMap
 * var addToMap = [along, line]
````

Sometimes there are properties or something that get added for styling 
`````
 * //addToMap
line.properties.size = 'large'
 * var addToMap = [along, line]
````

I manually edited these locally and didn't push them back up to the source repo sorry, it's on the to-do list :)

**Comment by stebogit** [comment]
OK @rowanwins, I can do that 👍 
So the changes I make in the `turf` "folder" of the `TURF-www` project are going to be committed also to the official `turf` source project, correct?

**Comment by rowanwins** [comment]
no, so that is part of the annoying thing at the moment. For changing the module docs I use the regular turf repo, I normally create a branch called `doc-changes`, then make the changes to a turf module as you normally would, then wait for the pull request to get accepted. Finally you're ready to go back to the turf-www repo and then cd into the turf directory and run `git pull origin master` and you're ready to go!

**Comment by rowanwins** [comment]
PS I suspect there has got to be a better way to do it all but I haven't figured it out yet :)

**Comment by stebogit** [comment]
Well it would be great if we could enforce these requirements with the linting tool already in place. Could we?

**Comment by DenisCarriere** [comment]
@stebogit We can definitely add some tests for this, or we could improve the handling in `turf-www`

**Comment by stebogit** [comment]
@rowanwins I have to admit [this](https://github.com/Turfjs/turf/pull/857) is a clear demonstration that in the end the ["annoying" flow](https://github.com/Turfjs/turf-www/issues/113#issuecomment-317166681) of updating `turf` before updating the docs in here is actually effective. 😄

If there isn't a more efficient flow that still allows these double checkings I'd just improve the tests on the `@example` in each `turf` module. Maybe we can even add a note in `CONTRIBUTING.md` or in the PR template

**Comment by DenisCarriere** [comment]
Anytime something is "annoying" we should change that.. lol

You'll like this: https://github.com/Turfjs/turf/issues/859

**Comment by stebogit** [comment]
That's definitely a more efficient flow! 😄
