### ISSUE TITLE
v5 docs

### ISSUE THREAD

**Issue by rowanwins** [Turfjs/turf-www#115]
Hey @DenisCarriere & @stebogit 

I've been thinking about a bit of a refresh of the turf docs to tie in the v5 release for a few reasons
- The current documentation.js dependency needs updating
- The current templating approach is less than ideal
  - I'd like to use documentation.js to generate a json output which I'd then use as a config file for a vue.js or react based site
- I'd like to move towards a single-page app rather than having all the docs on a single page
  - This would make managing the map much easier

What do you reckon? Any qualms if I mock up a screenshot or two or the proposed layout?

I'm thinking I wont make it in time for the release but I'll tinker at it as time allows.

**Comment by stebogit** [comment]
:+1: @rowanwins

**Comment by DenisCarriere** [comment]
👍 @rowanwins Looks good to me, I agree having a JSON object would be way easier to handle making a website in React.

Good stuff!

**Comment by rowanwins** [comment]
Just a quick report that I've made a start on this and it's going fairly well, I've got a single-page app functioning well. Outputting the jsdoc to json works well although it's taking some figuring out to then generate some of the strings particularly with links etc. Will flick a more detailed screengrab later in the week.

**Comment by DenisCarriere** [comment]
> single-page app functioning well

Nice! Looking forward to it!

**Comment by stebogit** [comment]
@rowanwins don't keep us hanging too long!! 😄

**Comment by rowanwins** [comment]
Just a thought that we should try and time the release of the docs with v5 given the amount of breaking changes there will be...

**Comment by DenisCarriere** [comment]
👍 @rowanwins yep! I don't think I'll be finished anytime soon.

How about we release this next major release before [State of the Map US](https://2017.stateofthemap.us/) (October 20-22).

**Comment by rowanwins** [comment]
Awesome @DenisCarriere I think that should be doable,  although with that deadline my preference is to use Vue because I'll be far more productive, you ok with that?

**Comment by DenisCarriere** [comment]
Vue or React, something with components. I've personally never used Vue, but I guess it would be a good time to learn to give you a hand.

**Comment by rowanwins** [comment]
Hey all,

Just a quick snippet of the progress. At the moment I'm pretty much just replicating what we've got while I work out how to parse the JSDOC/Documentation.js json. 

The next challenge is to try and incorporate some of the new modules which have options objects and working out how to display them nicely...

Single-page-ness is functioning well.  

Anyway coming together, hopefully another few nights and then I'll try and get inventive and snazzy them up a smidge more.

![progress](https://user-images.githubusercontent.com/6735870/31304598-7eb910bc-ab70-11e7-8e85-1fd2448b2792.png)

**Comment by DenisCarriere** [comment]
Nice! Looking forward to it! 👍

**Comment by rowanwins** [comment]
And now for something completely different! Thoughts @DenisCarriere & @stebogit ?
![possible](https://user-images.githubusercontent.com/6735870/31307625-e3263564-abb3-11e7-9e22-91cec3d9d13b.png)

**Comment by stebogit** [comment]
Love it!
Maybe you can make the map a little wider?
I think we should add colors and/or style to the outputs, maybe defining some basic rules, it would make the maps even more clear to read.
Keep up the good work @rowanwins! :+1:

**Comment by DenisCarriere** [comment]
👍 Really cool @rowanwins ! love it

**Comment by rowanwins** [comment]
Just a heads up this is almost there, mainly just tweaks to the build process now, content is pretty much sorted so I can probably aim to release over the weekend or whenever else suits.

**Comment by DenisCarriere** [comment]
👍 Sweet! I'll make sure I sync up the main v5.0 push for this weekend, it looks decent so far 🤞.

@stebogit I might take you up on your suggestion to remove any "backwards compatible v4.0" params and make all the methods strict, that way people are forced to learn the new v5.0 behavior using `options` as an `Object`.
