### ISSUE TITLE
TurfJS Logo (stickers)

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf-www#116]
# TurfJS Logo (stickers)

CC: @rowanwins @tmcw @stebogit @morganherlocker @mourner (thoughts?)

Since we are already on the path of giving TurfJS a facelift 💄 I've got some new logos for TurfJS.

Provided are all the files ready for printing on stickers! 🤓  🎉 .

https://www.dropbox.com/sh/d8fdz2yd4af1swq/AABof3MUu6DQH3oreeOerBIFa?dl=0

![image](https://user-images.githubusercontent.com/550895/31147953-5d5f0210-a859-11e7-8777-8c8789488e33.png)

![image](https://user-images.githubusercontent.com/550895/31147970-6c7c8696-a859-11e7-8e59-5fb836f6ab35.png)

**Comment by stebogit** [comment]
Great! 😍 
We might want also a `<T>` logo for the favicon?
What about a color-reversed set?

**Comment by rowanwins** [comment]
Nice one @DenisCarriere , something like this is long overdue. We should see if we can fund a global turf hack weekend in the bahamas for a few of us based on sticker sales!

Do you know what font has been used, I'll see if I can carry that through on to the site?

**Comment by DenisCarriere** [comment]
👍 I like `<T>` as favicon (great idea!)

> What about a color-reversed set?

The images are transparent PNG's and also some illustrator files, you apply the logo to any background color:

![image](https://user-images.githubusercontent.com/550895/31151435-6f4cca1e-a865-11e7-8b08-efab753dde6f.png)

**Comment by DenisCarriere** [comment]
> global turf hack weekend ~in the bahamas~

Hack weekend is a great idea (Bahamas might be a bit much).

We can use Twitter to track the Turf related project and send stickers to those who submit examples (obviously we will send stickers to all the contributors as well "no need for examples").

**Comment by DenisCarriere** [comment]
> Do you know what font has been used

Not too sure what font was used, it would be a good idea to match the fonts (as much as possible).

**Comment by rowanwins** [comment]
When I get home I'll check out the ai file and that might give me some clues re the font

**Comment by tmcw** [comment]
I kinda made the old logo in a hurry, maybe we should take advantage of the opportunity to spruce up the Turfjs brand, and at the same time switch to fonts that are available for free OSS use across platforms? This is with League Spartan & Source Code Pro:

![image](https://user-images.githubusercontent.com/32314/31156957-4726220e-a86c-11e7-915f-a2bd38c15eae.png)

**Comment by stebogit** [comment]
Yesterday I stumbled across this site: www.tailorbrands.com
Does anybody know it?
Never used it, but it seems a cool idea!

**Comment by DenisCarriere** [comment]
@tmcw 👍 Looks cool! The objective with this logo redesign would be to get Stickers!! 🚀

**Comment by DenisCarriere** [comment]
I like the font selection 👍

**Comment by stebogit** [comment]
What about this guys?
![logosample_bytailorbrands](https://user-images.githubusercontent.com/12717225/31161325-1698863a-a88b-11e7-832d-f71533048d3f.jpeg)

**Comment by morganherlocker** [comment]
Love this idea. When we decide on something, I'll make a bulk order and will send a bunch to anyone interested, with plenty of extras for passing along to friends and acquaintances. 

@tmcw I'm digging the circle logo and the new font. I'm inclined to just run with this, or perhaps add a small tesselation graphic next to the name to make it a bit more interesting on a sticker.

---

**Email me a physical address to morgan.herlocker@gmail.com with the subject line "TURF STICKERS", and I will ship a 'thank you' sticker care package to anyone interested, once they are printed.**

**Comment by rowanwins** [comment]
The font in @DenisCarriere original ai file appears to be [Montserrat](https://fonts.google.com/specimen/Montserrat) which is freely available and comes in lots of weights. 

I think I prefer the Monteserrat font used in @DenisCarriere version compared to @tmcw version. And it's relatively easy to work out a nice pairing font using http://fontpair.co/ 

And agree with @morganherlocker that it would be cool to add some sort of graphic element to a sticker, just need to work out what...

PS And sorry for downvoting your attempt @stebogit , I still love the rest of your work :)

**Comment by DenisCarriere** [comment]
I'm also good with @tmcw's circle logo! @morganherlocker Definitely run with that 👍 

I'm going to be at [State of the Map US](https://2017.stateofthemap.us) (October 20-22), you think we could have something ready by then?
