### ISSUE TITLE
Direct navigation to pages bug

### ISSUE THREAD

**Issue by rowanwins** [Turfjs/turf-www#121]
So it doesn't look like we can directly navigate to the pages at the moment, eg going to `http://turfjs.org/docs#bearing` fails, even though that's the url that gets shown if you navigate manually. 

This is tied in with the fact that we're now got a single-page app and how they handle urls.

I was using the[ 'history' ](https://router.vuejs.org/en/essentials/history-mode.html)mode for vue-router however for that to fully work you need to implement some server-side stuff which we can't really do because of the nature of github-pages.

So Im thinking we might need to go to `hash` mode which is more standard for single-page apps. This means our urls would look like `http://turfjs.org#docs/bearing`.

Thoughts/objections? 

cc @DenisCarriere @stebogit

**Comment by DenisCarriere** [comment]
Yep, this navigation using the URL seem to have an issue, we shouldn't be using any server-side magic for the static pages (vue-router).

Page not found also for [http://turfjs.org/getting-started](http://turfjs.org/getting-started).

Another odd thing was it can't view `@turf/random` (can't figure out why...)

**Comment by stebogit** [comment]
@rowanwins first of all great job on the new doc website!! 😍 
I wonder why though we didn't advertised it more, it's really worth noticing and I think we should spread the news. Actually I was not even sure it was already online... 🤔 
@DenisCarriere don't you think we should make more fuss about this?

Anyway, I don't know if you did any change but I could open directly the link to [`turf-bearing`](http://turfjs.org/docs#bearing) just fine or [`get-started`](http://turfjs.org/getting-started):

![screen shot 2017-11-12 at 12 36 11 am](https://user-images.githubusercontent.com/12717225/32697266-9ee731ba-c741-11e7-8e24-6c87584f28f0.png)

However when the page is loaded then you can't load a different module/link via url, but you have to click on the left menu. You can in a new tab though.

**Comment by rowanwins** [comment]
Hi @stebogit 

Yeah the page navigation is what this issue is about, I'll slightly need to restructure the urls to allow direct navigation.

Re promoting the changes to the docs - @DenisCarriere did put out a tweet. Not sure if you've got any other great ideas for how we'd get the word out there... I suspect people will find them naturally

**Comment by stebogit** [comment]
Maybe mentioning it in the CHANGELOG or releases file?

**Comment by rowanwins** [comment]
So I've tested this out, to confirm what my proposed changes look like
`http://turfjs.org/docs#bbox`
becomes
`http://turfjs.org/#/docs/bbox`

When a dud url is entered eg `http://turfjs.org/#/docs/sdfsf` it fallsback to `http://turfjs.org/#/docs/along`

Any dramas with this @DenisCarriere ?

**Comment by DenisCarriere** [comment]
@rowanwins What's the current issue with it now?? Seems to work just fine (I think right?)

http://turfjs.org/docs#bbox (does that not work for you?)

**Comment by rowanwins** [comment]
I could've sworn that didn't work last week @DenisCarriere !!!!

**Comment by DenisCarriere** [comment]
Lol! 🤣 I do remember it not working, but now it works, Magic!! 🎱
