### ISSUE TITLE
turfjs.org/docs/ is broken

### ISSUE THREAD

**Issue by andrewharvey** [Turfjs/turf-www#124]
The docs for turf used to be at http://turfjs.org/docs/ right? Now that's broken, http://turfjs.org/docs works, so perhaps this needs a redirect?

**Comment by DenisCarriere** [comment]
Correct, I think a redirect would be ideal.


## http://turfjs.org/docs/
![image](https://user-images.githubusercontent.com/550895/33053488-a42803d2-ce28-11e7-9de8-5be40cff7a0e.png)

**Comment by DenisCarriere** [comment]
@rowanwins Any thoughts on how we can handle that with VueJS?.. 🤔

**Comment by rowanwins** [comment]
Think I should be able to manage it

**Comment by andrewharvey** [comment]
If that redirect could retain the `#params` that would be ideal. Because a lot of links in the wild ([eg here](https://github.com/mapbox/mapbox-gl-js/issues/4095#issuecomment-336337337)) like this `http://turfjs.org/docs/#linesegment` should still end up at that point in the docs.

**Comment by rowanwins** [comment]
Roger that, will see how I go, thanks @andrewharvey . I did manage to kind of get things tidied last night but then got distracted trying to fix the bundle size :)

**Comment by DenisCarriere** [comment]
@andrewharvey For sure, we should preserve the previous URL references of TurfJS that way there's less broken links in the wild.

**Comment by andrewharvey** [comment]
http://turfjs.org/docs/ currently returns a 404. This is breaking a lot of links in the wild.

**Comment by rowanwins** [comment]
Yeah sorry @andrewharvey - still trying to find time to get on to this, the joy of trying to prioritise open-source work at 10pm :)

**Comment by andrewharvey** [comment]
@rowanwins I understand and realise we're all volunteers here. Could we re-instate the old docs until this is resolved, that takes the time pressure off this and means links aren't broken? Then once this is fixed you can roll out the new docs once again.

**Comment by rowanwins** [comment]
Let me take a look tonight @andrewharvey and I'll see if I can get it sorted. Unfortunantly even reverting is challenging because the old docs were for pre-v5 which means they didn't say anything about the options object.

**Comment by DenisCarriere** [comment]
@rowanwins I did some changes to fix this... hopefully it didn't break anything.. 🤞 (unfortunately I'm going to bed and I won't be able to test this until tomorrow)

**Comment by DenisCarriere** [comment]
The website should be working as intended again:

The following links work:

- http://turfjs.org/docs
- http://turfjs.org/docs/#bearing
- http://turfjs.org/docs#bearing

**Comment by andrewharvey** [comment]
Thanks for fixing this!

One minor point, the docs used to accept lower case but now they don't so links in the wild like `http://turfjs.org/docs/#linesegment` don't go to the correct anchor, it's now `http://turfjs.org/docs/#lineSegment`. But at least they get to the docs page now.
