### ISSUE TITLE
UX issues in new documentation - Full text search?

### ISSUE THREAD

**Issue by peterbodo** [Turfjs/turf-www#125]
Hello,

Thanks for your work and the new site is really cool, however, it has significant issues with usability.

In the previous site you could use browser search on the whole content. It does not work any more.
(of course that was to much content for a page, I admit)
E.g. I searched for hull, and of course I did not get any results. 
With a web search I have found that I would need to search on concave. 
This is quite uncomfortable, since module-names are not self-explanatory at all.

Since the detailed desccriptions most often contain the important information, a full-content serac would solve this problem.

(note: although it will not solve the problem, that the new site cannot be found by serach engines :(, that would need anotherr solution).

Cheers,
Peter

**Comment by rowanwins** [comment]
Gday @peterbodo 

Thanks for the suggestion, I had not thought of that. I think what you are suggesting might be somewhat doable. I'm currently running some updates on the docs so I'll see if I can work it in.

Cheers

**Comment by peterbodo** [comment]
I mean, those who know the modules in all detail won't recognise this problem (but they probably don't need the documentation :) ). Thanks indeed.

**Comment by peterbodo** [comment]
One more thing:
People rarely use on-site search.
E.g. you do not search within stackoverflow, but search google and will find probably the best answer on stackoverflow.

Now google searches do not show turfjs.org for querys like:
"turf hull"
"turfjs hull"
but neither
"turfjs concave"

**Comment by rowanwins** [comment]
yeah that's a bit problematic. I might take a squiz and see if using [nuxt.js](https://nuxtjs.org) is an option to pre-render all the pages, [supposedly](https://github.com/nuxt/nuxt.js/issues/19) this could work and would make the site and I believe the site would be more crawlable google

**Comment by DenisCarriere** [comment]
Making it "crawlable" and easy to find stuff is a must, I agree we should probably go back to the full page with all the modules loaded at once, that way you can easily CTRL+F (search) for what you want directly in the page and keep scrolling down to hit what you want.

👍 @rowanwins Great start, we just need to keep working on it to make it a bit more searchable friendly.

**Comment by stebogit** [comment]
> easily CTRL+F (search)

:+1:

**Comment by rowanwins** [comment]
Mmm not sure about reinstating a full page of docs, I found them kinda unwieldy and it also reintroduces the problem of what to do with maps.

Im wondering if an alternate solution is to add the module description as something which can be searched... eg when you use the search box and type in 'hull' then both the `concave` and `convex` modules would be shown because both their descriptions contain the word hull. 

Does that sound like a good middle ground @DenisCarriere @stebogit @peterbodo ?

**Comment by peterbodo** [comment]
@rowanwins thanks, but I think that would not be an optimal solution.

Documentations are quite often a one pager (e.g. mapbox) and I think it is quite necessary to serach them (ctrl-f) and find descriptions in context.

On the other hand I don't think the documentation and the examples has to be on one page (again, e.g. mapbox).

I have rarely found an extra value in seeing the turf example maps, and they are static anyway, so a good image could do the same (if you want visualisation) or even better with little legends, explanations. 

I know it leads far from what you have now, so I do not want to suggest a complete redesign.

One good middle ground I could suggest:

-have the whole documentation as a one-pager without preloaded map examples.
-showing a map example has to be triggered by a user click

that would be quick, serachable, and having the map examples on request as well. 

What do you think?

**Comment by stebogit** [comment]
I do like the one page structure and the easy searchability, as @peterbodo pointed out it's often a standard. However I do see great benefit in having a rendered example, cause 90% of the time (and that's our job to make them intuitive) they allow the user to get immediately what exactly the module does without looking at the code. That I think is the goal of the maps.

My suggestion would be having a single page with the current map element fixed on the right and the content scrolling on the left, replacing the map's content when the title of the new module text hits the top of the page or something.

**Comment by DenisCarriere** [comment]
👍 One page structure (Sorry @rowanwins 😝)

I'm 👍 for @stebogit & @peterbodo' suggestions, I know it would take some time to restructure the website to that, no rush...

**Comment by rowanwins** [comment]
Alright alright I know when I'm outvoted!

Might not actually be too bad converting back to a large single page so I'll see how I go.

**Comment by DenisCarriere** [comment]
haha :) Only ❤️  for you @rowanwins

**Comment by rowanwins** [comment]
Righteo well I've made a reasonable start converting the docs back into one big page. And I'm now generating the docs using `Nuxt` which spits me out compiled versions which are better for search engines. Still a bit to go, mainly around the maps behaving nicely on scroll, but it's getting there...

**Comment by rowanwins** [comment]
New docs were published last night which go back to a single page for all the modules. Take a look @peterbodo and if you're happy feel free to close this issue. These are also pre-generated so google should work better now.

**Comment by peterbodo** [comment]
Thanks a lot, @rowanwins 
okay, beautiful. really cool.
Only that I tried to scroll down a lot to the terra incognita where maps have not been loaded yet, and my Chrome went "ah, Snap" :).
So it is a bit heavy like this, we knew that.

I understand that you really want to demonstrate with maps. Since these examples are basically non-interactive and static: a nice and easy solution would be just using screenshots. I don't want to be an asshole, and it is visible how much work has been put into these live examples, but it just seems so much lighter.

Being an asshole anyway, I can also mention that a good drawing would be much easier to understand in many cases. Like in case of bearing, you just see two points on a map. 

BUt in summary: if I am not inpatient, the page loads nice, and it is searchable, so thanks a million.

If you want to comment on this, please, do so, but otherwise, you can close the issue.

Thanks a million

**Comment by rowanwins** [comment]
Gday @peterbodo 

Yeah the map thing certainly has it's challenges :) That said I've not seen it go snap yet so not sure what's going on there, I'll do some digging to see if I can replicate it....

We've started talking about [graphics for the docs over here](https://github.com/Turfjs/turf/issues/1140), it's another thing that needs doing :)  Putting the maps on the screen was a relatively easy win because we could leverage the example code snippets so it was relatively straightforward.

Anyway constructive feedback is always welcome so all good :)
