### ISSUE TITLE
Fix built size

### ISSUE THREAD

**Issue by rowanwins** [Turfjs/turf-www#126]
Noticed last night in tidying up the sidebar stuff that the size of our built app is enormous (eg 8MB). Doing some work to cut this right back to something way more appropriate.

**Comment by DenisCarriere** [comment]
Another thing to note is it's not Minified yet, it's uncompressed... so we can go ahead and compress it and it would reduce it by a lot.

**Comment by rowanwins** [comment]
Yeah, that would certainly be a step in the right direction.
