### ISSUE TITLE
_nuxt issues

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf-www#131]
## _nuxt issues

@rowanwins I've patched the website to make it work, however there was a few issues when deploying the new website.

- `_nuxt` isn't recognized by GitHub pages, folder is treated as private.
> Solution, I renamed it to `js/`
- Modified manifest `"/_nuxt/"` => `"/js/"`
- Modified `src` from for `index.html` => `js/`
- Modified `Docs/index.html` &  `Getting-Started/index.html` => `../js/`
- Moved all website related files to `docs`, however this can be changed back to main repo. It's a bit cleaner when all the hosted files are in one folder.

CC: @rowanwins Have a look at these, maybe there's a config we can change that will build it the way we want it, the main issue was to change `_nuxt/` => `js/`.

**Comment by rowanwins** [comment]
No worries @DenisCarriere leave it with me, glad you managed to get some temporary fixes sorted.

**Comment by DenisCarriere** [comment]
✋ High five
