### ISSUE TITLE
TOC links broken in http://turfjs.org/docs/

### ISSUE THREAD

**Issue by andrewharvey** [Turfjs/turf-www#135]
Following up from #124, the links are broken again. Visiting http://turfjs.org/docs/ then selecting any links in the TOC takes you to http://turfjs.org/docs/docs#bearing which then shows "This page could not be found".

/cc @rowanwins

**Comment by rowanwins** [comment]
Thanks for the report @andrewharvey I'll get it sorted tonight. I pushed a quick update today because all the maps we're broken due to an expired access token, not sure what might've affected those links

**Comment by rowanwins** [comment]
Gday @andrewharvey 

Should all be resolved now, don't think it had anything to do with my changes thisafternoon. Minor tweak to how the routing was handled and all sorted.

**Comment by andrewharvey** [comment]
Thanks for fixing this @rowanwins!
