### ISSUE TITLE
Make the documentation site responsive so it works on mobile/tablet

### ISSUE THREAD

**Issue by danielduhh** [Turfjs/turf-www#136]
Lets make turfjs.org mobile friendly.. ( I can help 😎)

**Comment by rowanwins** [comment]
Hi @danielduhh 

Yeah that would be nice especially if you're offering to help! 

The trickiest bit will just be working out the sidebar.

Currently the site is powered by [Vue.js](https://vuejs.org/) and [Nuxt](https://nuxtjs.org/)for static rendering. Components are provided by [iview](https://www.iviewui.com/). You might be able to play with the [responsive layout options](https://www.iviewui.com/components/grid-en#Responsive Layout) to get things working nicer although it had pretty limited options.

If you're keen to get started let me know. I have one commit I should push up which'll make the build process a bit smoother. And I can explain a bit more about where to look etc if you're not familiar with Vue & Nuxt.

Thanks!
Rowan

**Comment by danielduhh** [comment]
@rowanwins I'd love to help. I can take a look at it this weekend. Did you push that commit ?

**Comment by rowanwins** [comment]
Gday @danielduhh 

I've just pushed up the fix so you should be right to go. Should be a matter of cloning the repo and then 
````
npm install
npm run start
````
Once you've made your changes you can run the following to spit out the static files
````
npm run generate
````
I normally then use something like [static-server](https://www.npmjs.com/package/static-server) just to check the final generated docs. 

If you want just push up the changes to the src folder and I'll do the final `generate` cmd and check through things.

Thanks so much for looking at this!

**Comment by 64J0** [comment]
I've been working in this now. Soon I'll submit some changes in a pull request.

**Comment by 64J0** [comment]
Where is that `src/assets/config.json` from? It seems to give some warnings when compiling the nuxt static files.

**Comment by JamesLMilner** [comment]
Brought up again here https://github.com/Turfjs/turf/issues/2418

**Comment by JamesLMilner** [comment]
I am currently looking into resolving this. Hope to have a PR up soon.

**Comment by HarelM** [comment]
I think this was resolved by #181, wasn't it?

**Comment by JamesLMilner** [comment]
@HarelM yes! 😄
