### ISSUE TITLE
https error

### ISSUE THREAD

**Issue by mhkeller** [Turfjs/turf-www#140]
when trying to access the site over https it says it's unavailable. if you're serving the site over gh-pages, you can now tick "Enforce HTTPS" or something like that in the settings to serve over ssl.

**Comment by morganherlocker** [comment]
Update here: a few of my domains had been registered many years ago on a legacy provider that was particularly difficult to work with. I recently ported my first of these legacy domains over to https on a lower traffic site, so I feel confident that I can now port the turf site over without disruption. I will update here when I have made the switch.

**Comment by morganherlocker** [comment]
Done: https://turfjs.org/

Thanks for flagging and waiting @mhkeller!

**Comment by mhkeller** [comment]
Nice great work!

**Comment by wesinator** [comment]
http://turfjs.org/ supports HTTPS, but doesn't enforce 

Happy new year!
