### ISSUE TITLE
Data in Turf (long/lat coordinates)

### ISSUE THREAD

**Issue by stebogit** [Turfjs/turf-www#141]
Although it is quite clear that Turf is based on standard WGS84 coordinates (long/lat) by reading the [project readme](https://github.com/Turfjs/turf#data-in-turf), I think it would be useful to have it also clearly stated on the website homepage.

Ref https://github.com/Turfjs/turf/issues/1520

**Comment by morganherlocker** [comment]
Closed in https://github.com/Turfjs/turf-www/pull/142
