### ISSUE TITLE
Awesome turf

### ISSUE THREAD

**Issue by Timtech4u** [Turfjs/turf-www#147]
Would be nice to have a list of awesome resources for Turfjs
I wrote an article [here](https://medium.com/@timtech4u/geospatial-analysis-with-javascript-turf-js-%EF%B8%8F-b6a73de50286) and was seeking for a appropriate place to share it.

**Comment by rowanwins** [comment]
Hey @Timtech4u 

Yeah it would be nice to have something. We could include a page on the doco site.

Or alternatively we could setup an `awesome-turf` repo similar to what a number of other libs do (eg [vue](https://github.com/vuejs/awesome-vue) ). This would probably be simpler to maintain and for ppl to contribute to. The downside being it is seperate from the rest of the docs.

I think I'd lean towards the later to make maintenance a bit easier...

What do you think @Timtech4u ?

**Comment by Timtech4u** [comment]
Hi @rowanwins , thanks for the feedback.

I was also going to suggest an *awesome-turf* repo, I agree it'll be quite easier to contribute to and maintain, and also I can work on the initial setup 👍 

While the rest of the docs remains on the site, we could add a link  for *awesome-turf* to the [Getting Started Page](http://turfjs.org/getting-started) , that'll help users find it easily.

**Comment by rowanwins** [comment]
Hey @morganherlocker 

I don't have sufficient permissions over the Turf org to set this up - are you able to set up a repo for @Timtech4u (and perhaps bump up my permissions :) )

Thanks

**Comment by Timtech4u** [comment]
Hi @rowanwins, I believe this isn't a problem anymore.
I just got access to https://github.com/Turfjs/awesome-turf from @morganherlocker :+1:

**Comment by rowanwins** [comment]
Awesome - looking to see what happens :)
