### ISSUE TITLE
OpenStreetMap attribution on the turfjs.org homepage

### ISSUE THREAD

**Issue by harry-wood** [Turfjs/turf-www#154]
I feel someone should mention... The https://turfjs.org homepage has a couple of web maps which use OpenStreetMap data rendered/hosted by mapbox, but no attribution for OpenStreetMap.

It's front and centre on the homepage, so you'll want attribution to be quite minimalist to avoid cluttering the design. I see `attributionControl` set to `false` here: https://github.com/Turfjs/turf-www/blob/master/src/pages/index.vue#L73 so I guess somebody thought about this, but the result seems wrong. Your chosen tile renderer/host (Mapbox) gets quite a prominent logo twice, while the volunteer mappers of OpenStreetMap ...nada.

<img width="368" alt="Screenshot 2020-01-29 at 00 41 24" src="https://user-images.githubusercontent.com/227525/73318563-b7a38880-4231-11ea-9c8b-f98390bb8789.png">

**Comment by rowanwins** [comment]
Hey @harry-wood 

I suspect that was probably my fault, no harm to the OSM movement was meant, I suspect if anything I was probably trying to deactivate the mapbox logo and got distracted while dev-ing. I try and get it rectified when I get a chance

Cheers
Rowan

**Comment by rowanwins** [comment]
Done
