### ISSUE TITLE
link to submodules

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf-www#17]
Each example should have a link to a submodule. Examples are great, but readmes provide nitty-gritty api specifics.

Alternative: We could generate "API" docs by pulling down README files for each submodule and wrapping it in a nice shell. I am still not sure if this is worth the trade off of potential syncing problems.

**Comment by lyzidiamond** [comment]
We have the docs in place, but should each doc page link to its submodule?

**Comment by morganherlocker** [comment]
turfjs.org docs are now primarily focussed on api docs, so I think this is resolved now. We should *maybe* still link to the sub modules somewhere, but let's start another issue if necessary.
