### ISSUE TITLE
Documentation links not working, not possible to open any item

### ISSUE THREAD

**Issue by answerquest** [Turfjs/turf-www#176]
- Go to https://turfjs.org/getting-started
- On the left sidebar we see a glossary  / listing of various functions.
- Try clicking on any
- Site does not navigate to them
- Upon clicking many items, you'll notice the URL in the browser starts piling on /docs/docs/docs/docs....

I had visited this site last year and remember that clicking on an item would take me at least to that section's page and the item's documentation would be in there. But now the user is just stuck on the "getting started" page forever. Ctrl+clicking the items also doesn't help as they're not real hyperlinks.

**Comment by answerquest** [comment]
I'm able to access the documentation by manually going to this URL: https://turfjs.org/docs/index.html
I have to avoid clicking the left sidebar menu and rely on Ctrl+F to locate the desired function's documentation.
So the content is there - linking is broken. And from the /docs/docs/docs/... effect it seems there's a relative adding of urls happening.

**Comment by laurenwalker** [comment]
I can confirm that this bug is still happening for me as well

**Comment by JamesLMilner** [comment]
Thanks all for raising - this is resolved now.
