### ISSUE TITLE
Building turfjs-starter

### ISSUE THREAD

**Issue by dayjournal** [Turfjs/turf-www#177]
I have built a build environment that allows me to easily start "Turf.js" with a combination of "MapLibre GL JS," "Vite," and "TypeScript."
Do you think I should import this starter into this repository as a Getting started for builds?

starter
https://github.com/dayjournal/turfjs-starter

example
https://dayjournal.github.io/turfjs-starter

**Comment by rowanwins** [comment]
Hi @dayjournal - that sounds like a fairly opinionated tech stack, and given that TurfJS plays nicely with pretty much every front-end framework and mapping lib without any special config I'm not sure there is too much value in listing it as a starter environment.
But thanks for thinking of us and I'm glad you're getting good use of of Turf :)
