### ISSUE TITLE
example code styles

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf-www#18]
Let's stick to the [airbnb style guide](https://github.com/airbnb/javascript). We can automate this in one pass, then encourage the use of [editorconfig](http://editorconfig.org/) from there. This is not normally a huge deal to me, but people will probably be copy/pasting from these regularly, so we should keep the code clean.

**Comment by lyzidiamond** [comment]
I agree with the sentiment of keeping the code clean, but is this necessary?

**Comment by morganherlocker** [comment]
yeah, agree @lyzidiamond. this only applied with previous /examples stuff. (maybe revisit if jsdocs examples get wacky, but fine for now)
