### ISSUE TITLE
Error with map not showing

### ISSUE THREAD

**Issue by ByMykel** [Turfjs/turf-www#186]
It's really a dumb error. Some occasions when you have 2 example's description on screen you end up with map not showing.

https://github.com/Turfjs/turf-www/assets/38622893/5ec809b8-a84d-4b05-aefa-7cc823c59b90

**Comment by smallsaucepan** [comment]
Hi @ByMykel . Thanks for informing us of the error. The attached video doesn't play though, so perhaps you can attach some screenshots instead?

**Comment by ByMykel** [comment]
> Hi @ByMykel . Thanks for informing us of the error. The attached video doesn't play though, so perhaps you can attach some screenshots instead?

Can you watch this gif?

![ezgif-2-6a8eba90ca](https://github.com/Turfjs/turf-www/assets/38622893/445479c0-1630-42df-82c7-4fee941cfbba)

**Comment by smallsaucepan** [comment]
That works. Thank you. We'll take a look.
