### ISSUE TITLE
No current way to search through docs

### ISSUE THREAD

**Issue by jkkDTN** [Turfjs/turf-www#192]
Hi all 👋 

Looking forward to the release of v7! It also sounds like the docs part of the site will bring a lot of benefits as well!!

A feature I was hoping could be ported over from the previous version is the ability to search/filter through the docs for a specific part of the API.

I used the search feature extensively with the old docs site, and I have a bit of "user frustration" when trying to use the new docs site because of not being able to search/filter through it.

Thanks!

**Comment by smallsaucepan** [comment]
Thanks for noting this @jkkDTN. This is our next feature to add. Hopefully be resolved in the first half of the week.

**Comment by artu-ole** [comment]
@smallsaucepan 
Does the search not function any more or is it just me?
![brave_NbU9ZRXxCL](https://github.com/user-attachments/assets/1d88960b-5584-4758-b6a1-7df1957308f3)
Could it be that some doc tags are missing in the latest release as it seems that if I omit docusaurus tag filter from request I get results back from the search query? i.e. query works if one removes `["docusaurus_tag:default","docusaurus_tag:docs-default-7.0.0"]` from `facetFilters` payload parameter
