### ISSUE TITLE
Turf 7 docs not on turfjs.org

### ISSUE THREAD

**Issue by nebain** [Turfjs/turf-www#196]
It looks like turfjs.org is still showing the docs for Turf 6. Docs -> Getting Started refers to @turf/turf@6, and several functions (intersect, difference, etc) under API are still showing their old Turf 6 signatures.

**Comment by smallsaucepan** [comment]
Thanks for raising this @nebain. Hopefully the v7 docs will be available on the website in a few days.

**Comment by smallsaucepan** [comment]
v7 docs now available on the website 👍
