### ISSUE TITLE
playground in browser console

### ISSUE THREAD

**Issue by pahuta** [Turfjs/turf-www#201]
Previously I can open browser console and turf was exposed as global variable (I guess it was `_`). Currently it's not available. Please add this feature back.

**Comment by smallsaucepan** [comment]
Hi @pahuta. This is the repository for the turfjs.org website. Are you saying you used to be able to do this on turfjs.org and can't anymore?

Or do you mean in your own custom app that uses Turf? If this case best raise an issue on the repo for the library https://github.com/Turfjs/turf/issues

**Comment by jcready** [comment]
[This feature was incredibly useful](https://github.com/Turfjs/turf/issues/2711). Please expose `window.turf` on turfjs.org like it used to be. Thank you.

**Comment by jcready** [comment]
This isn't so much a feature request as it is a bug. Pretty much all of the examples in the API documentation don't actually show the result of the executed code (showing the result in a map is not the same). Previously the user looking at the example code could just execute it directly in their browser console to see the result. Now that the user can no longer do that the code in the examples are not all that helpful.

**Comment by smallsaucepan** [comment]
Thanks @jcready. Understand where you're coming from 👍

**Comment by smallsaucepan** [comment]
@pahuta @rianonehub @jcready - thanks for highlighting how useful this was.

![Screenshot 2024-10-25 at 11 45 38 AM](https://github.com/user-attachments/assets/39487ec4-88d8-4bc1-ac6a-508f3e617cef)

It's only on the API pages (not the home page, blog, etc) though from how you've described using it that should be fine.

**Comment by pahuta** [comment]
Thank you, @smallsaucepan 🚀
