### ISSUE TITLE
Searching A Keyword With No Results Yields `undefined`

### ISSUE THREAD

**Issue by BradyDouthit** [Turfjs/turf-www#203]
Searching any term that does not have results brings up a link with the text `undefined`:
![image](https://github.com/user-attachments/assets/04ecf90c-9329-4490-9b33-799e59f48752)

After clicking on `undefined`, it searches for it:
![image](https://github.com/user-attachments/assets/916d849b-3962-4b52-af05-bc893569d562)

Browser: Chrome v127.0.6533.122

**Comment by smallsaucepan** [comment]
Hi @BradyDouthit. Search wasn't working at all and has now been fixed.

![Screenshot 2024-10-02 at 5 03 08 PM](https://github.com/user-attachments/assets/c2afca17-5915-4388-b2e3-ec029836504e)

Typing in gibberish sometimes suggests undefined, though I think it's the crawler picking up mentions of `undefined` in the docs and offering it as a legitimate suggestion.

Closing, though please sing out if this isn't exactly resolving the issue for you.
