### ISSUE TITLE
There are some broken links on the site.

### ISSUE THREAD

**Issue by tpgus** [Turfjs/turf-www#208]
The link to the 'shortestPath' method section in the API documentation is broken.

[https://turfjs.org/docs/api/shortestPath](https://turfjs.org/docs/api/shortestPath)

**Comment by meows** [comment]
I also see broken docs.

**Comment by smallsaucepan** [comment]
Thanks @meows. shortestPath as well? Or a different page?

**Comment by tpgus** [comment]
@smallsaucepan 

Here is the list of broken links  and page url I found.

- [Leszek Rybicki](http://leszek.rybicki.cc/) found on https://turfjs.org/docs/api/bezierSpline
- [Chaikin's algorithm](http://graphics.cs.ucdavis.edu/education/CAGDNotes/Chaikins-Algorithm/Chaikins-Algorithm.html) found on https://turfjs.org/docs/api/polygonSmooth
- [pysal](http://pysal.readthedocs.io/en/latest/index.html) found on https://turfjs.org/docs/api/moranIndex
-  [http://edndoc.esri.com/arcsde/9.0/general_topics/understand_spatial_relations.htm](http://edndoc.esri.com/arcsde/9.0/general_topics/understand_spatial_relations.htm) found on https://turfjs.org/docs/api/booleanEqual#description

**Comment by smallsaucepan** [comment]
Thanks @tpgus. Could I please ask you raise those broken links as an issue over at https://github.com/Turfjs/turf ?

The shortestPath page was totally broken (which we fix here in the website repo) but the links to external sites are found in the library repo, and need to be fixed there.

**Comment by tpgus** [comment]
Thanks @smallsaucepan.

I created a new issue at https://github.com/Turfjs/turf as you suggested.

https://github.com/Turfjs/turf/issues/2737
