### ISSUE TITLE
Use base.css?

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf-www#24]
This could lead to a bit more code-sharing etc.

**Comment by morganherlocker** [comment]
Made a branch that uses base. I like the current turf-www look, but think it would be useful to use base for example controls, device formatting, etc. As is, we will need to override a few styles that clash with the current site.css (or switch all out to mapbox style docs).

https://github.com/Turfjs/turf-www/pull/25

**Comment by tmcw** [comment]
deployed
