### ISSUE TITLE
Sample datasets for node.js examples

### ISSUE THREAD

**Issue by rukku** [Turfjs/turf-www#28]
Would it be possible to include the geojson files used in the examples? I come from a GIS background and we usually bundle our datasets so that we can get a feel as to how the functions work and so that we can see the output immediately. It isn't an issue with the web usage of turf.js as we can see the source and the datasets are pulled by the code but the lack of sample/test datasets can be a problem for the node.js use cases where processing is done offline. Or it might just be with my inexperience in using node.js. Just my $0.02.

**Comment by morganherlocker** [comment]
linked to an example of DC fire departments in geojson.io under the new "Data" section of the docs

**Comment by morganherlocker** [comment]
http://turfjs.org/examples.html

**Comment by rukku** [comment]
Awesome! Thanks!
