### ISSUE TITLE
what is turf section

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf-www#30]
Explain what turf is and what you might want to use it for. Explain a bit about what spatial processing/analysis is.

**Comment by lyzidiamond** [comment]
Started making notes for this in a gist: https://gist.github.com/lyzidiamond/0b45f37cebd0f873da53

**Comment by lyzidiamond** [comment]
This is on `/static/docs`, plus we have the guides... okay to close?

**Comment by morganherlocker** [comment]
:+1:
