### ISSUE TITLE
explicitly explain interactive examples

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf-www#31]
- http://turfjs.org/examples/turf-within/
- http://turfjs.org/examples/turf-tin/
- etc

It is difficult to tell that these accept user input at the moment.

cc @lyzidiamond

**Comment by lyzidiamond** [comment]
:+1: :star: :vertical_traffic_light:

**Comment by lyzidiamond** [comment]
This feels resolved with current doc. Closing.
