### ISSUE TITLE
Examples vs API

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf-www#32]
I like how the [mapbox.js docs](https://www.mapbox.com/mapbox.js/api/v2.1.4/) separate out examples from the API. The current examples are good at showing how you can put things together, but are too complicated if you are just looking to understand the parameters.

![](https://dl.dropbox.com/s/vbcez5xm4ko0nyq/Screenshot%202015-01-05%2016.59.55.png?dl=0)

**Comment by lyzidiamond** [comment]
I was just about to post a similar issue. A first pass of API docs could just be what's already in the READMEs from the individual modules (list [here](https://github.com/Turfjs/turf#features)).

**Comment by lyzidiamond** [comment]
Going to close this, as we're covering this in other issues.
