### ISSUE TITLE
add generic type to geojson.js

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf-www#36]
We need a way to specify that an argument can be any valid GeoJSON root object. Ideas:

* GeoJSON
* We would add a `Geometry` type and then this simplifies to `{Feature|Geometry|FeatureCollection}`
* Any
* GeoJSONObject

**Comment by morganherlocker** [comment]
@tmcw related: FeatureCollection of X

**Comment by morganherlocker** [comment]
going to run with "GeoJSON" for now. We can change it if we decide differently.

**Comment by tmcw** [comment]
:+1: done, GeoJSON
