### ISSUE TITLE
add function arguments to titles

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf-www#37]
![2015-01-07 at 5 28 pm](https://cloud.githubusercontent.com/assets/32314/5654608/9a5f37ba-9692-11e4-9bb2-92a53e3935db.png)

**Comment by lyzidiamond** [comment]
@tmcw do you still think we should do this?

**Comment by tmcw** [comment]
Hm, I think we should keep it open. I see it working really well in some docs, but also our docs are 'working' fairly well so we might want to keep them the same.

**Comment by tmcw** [comment]
No longer think this is a good idea.
