### ISSUE TITLE
turfjs.org down

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf-www#41]
Doing some tinkering and it looks like the new deploy script does not generate a CNAME record.

**Comment by morganherlocker** [comment]
https://github.com/Turfjs/turf-www/commit/9679906fc4967d6974d5c524f5fdc733d4d763d7

added CNAME to deploy script and it seems to be routing properly to [turfjs.org](http://turfjs.org/) now

cc @tmcw

**Comment by tmcw** [comment]
![image](https://cloud.githubusercontent.com/assets/32314/5692531/9bed93d8-98c7-11e4-86c1-04e983fd9ecf.png)

My bad, was in a struggle with the whole toolchain last night and the CNAME bug didn't propagate immediately so I missed it.
