### ISSUE TITLE
Recreate Examples

### ISSUE THREAD

**Issue by lyzidiamond** [Turfjs/turf-www#50]
Per #32, we have created API Documentation that encompasses a lot of the Examples from http://turfjs.org/examples.html. We had discussed creating more interesting examples that combine a variety of turf modules to do practical/topical/creative things.
## Next steps:
- [x] for now, remove the link to /examples.html from the header (on approval from @tmcw and @morganherlocker)
- [ ] decide on a technical structure for populating examples (static site generation?)
- [ ] populate examples  -- can pull from blog posts, our own tasks, etc. and can be literate and well-commented

**Comment by morganherlocker** [comment]
> for now, remove the link to /examples.html from the header

yeah lets cut it for now.

**Comment by lyzidiamond** [comment]
Per https://github.com/Turfjs/turf/pull/235, bumping this. Can we try to get a new examples page up on the site and remove /examples the week after next? @tmcw @morganherlocker

**Comment by tmcw** [comment]
Yep, I don't have a lot of bandwidth for this currently, though - might be able to help with this later this week.

**Comment by lyzidiamond** [comment]
Yeah, I'm at the conference this week, but I'll pound away at it when I can. Seems like a good focus for next week.

**Comment by rowanwins** [comment]
Hi @tmcw @morganherlocker @DenisCarriere @lyzidiamond 

I've taken a look at this and have made some progress in a fairly sensible way I think but I thought I'd run it by whoever is interested for a sanity check. Basically my goal was to put the example maps back in there with a minimum of effort. 

So what I've done is based on the `@example` snippet that is already in each module. To display the example I've added a new tag in the jsdocs called `@exampleFeaturesToAddToMap` (for lack of a better name) , this tag gets processed during the build and for each module we end up with a little script section which 
1. Creates a map with an id based on the module name (this enables multiple maps on the page)
2. Adds a `@example` snippet 
3. Adds the `@exampleFeaturesToAddToMap` to the map.

![IProgress](https://www.dropbox.com/s/sbya5yewr9aceon/exampleMap.jpeg?dl=1)

Benefits of this approach is that it's really minimal effort, and we could also incrementally add the maps to the docs by just doing a check if the `@exampleFeaturesToAddToMap` property is in the jsdocs.

Downside is that it introduces a new jsdoc tag which isn't standard but perhaps as long as we document it it's ok?

Anyway if you reckon the approach is ok I'll put in a pull request where you can see the actual code (< 100 lines of code)

Cheers

**Comment by DenisCarriere** [comment]
@rowanwins I really like incorporating the Map idea, however I'm not supporting of adding the new JSDocs tag. You're heading in the right direction by using the `@example` from the JSDocs.

Here's a solution that might work, what if you create the `FeaturesToAddToMap` from the variable that is defined by `//={variable name}` at the end of the JSDocs. Almost all of the JSDocs in Turf is using this type of syntax. You can also load multiple GeoJSONs to the map by simply adding more `//=` to the end of the example JSDocs.

```javascript
 * @example
 * var pt = {
 *   "type": "Feature",
 *   "properties": {},
 *   "geometry": {
 *     "type": "Point",
 *     "coordinates": [-90.548630, 14.616599]
 *   }
 * };
 * var unit = 'miles';
 *
 * var buffered = turf.buffer(pt, 500, unit);
 * var result = turf.featureCollection([buffered, pt]);
 *
 * //=result
 */
```

## Two Maps?

If you have an `input` & `output`, then maybe it would be best to have two maps if two `//=` are present.

- If one `//=` is present, create 1 map.

- If two `//=` are present, create the first **input** map using the first `//=` and the last `//=` is the output map.

- If multiple `//=` are present, create the first **input** map using all `//=` except the last one.

```javascript
 * @example
 * var features = {
 * "type": "FeatureCollection",
 * "features": [
 *   {
 *     "type": "Feature",
 *     "properties": {
 *       "combine": "yes"
 *     },
 *     "geometry": {
 *       "type": "Polygon",
 *       "coordinates": [[[0, 0], [0, 1], [1, 1], [1, 0], [0, 0]]]
 *     }
 *   },
 *   {
 *     "type": "Feature",
 *     "properties": {
 *       "combine": "yes"
 *     },
 *     "geometry": {
 *       "type": "Polygon",
 *       "coordinates": [[[0, -1], [0, 0], [1, 0], [1, -1], [0,-1]]]
 *     }
 *   },
 *   {
 *     "type": "Feature",
 *     "properties": {
 *       "combine": "no"
 *     },
 *     "geometry": {
 *       "type": "Polygon",
 *       "coordinates": [[[1,-1],[1, 0], [2, 0], [2, -1], [1, -1]]]
 *     }
 *   }
 *  ]
 * }
 *
 * var dissolved = turf.dissolve(features, 'combine');
 * //=features
 * //=dissolved
 */
```

**Comment by morganherlocker** [comment]
Noting that the previous interactive example used @tmcw's [rpl](http://www.macwright.org/2014/11/05/rpl-1.html), which was able to find and auto-render geojson or other types of in a reasonable way. The examples are designed around this syntax, so we may want to mimic that functionality, or resurrect rpl-www (needs a maintainer).

**Comment by rowanwins** [comment]
Thanks for your thoughts @DenisCarriere & @morganherlocker 

Re Denis' suggestion 1 of just showing the `//=result` sounds doable, and if I read morgan's suggestion of rpl correctly this would perhaps provides one mechanism to do that... 

**Sidenote:** I always found those `//=` bits in the code block examples a bit confusing, I was never quite sure why they were there. Should they be stripped out of the code block examples? 

Anyway I would be happy to implement this approach bearing in mind that would probably require just as much documentation as my approach above. I'll take a little bit of a look at it and see if I can get it going in a straightfoward manner. My only hesitation having not tried it is does add too much complexity for something I've already done with <100 lines (probably 20 lines I think without counting :) ). 

Another sidenote: We also need to work out what we do with those methods which don't return features, for example `@turf/area` or `@turf/bearing'. Do we just not have example maps for these modules?

Anyway stay tuned and I'll have a bit more of a think and play

**Comment by morganherlocker** [comment]
> Another sidenote: We also need to work out what we do with those methods which don't return features, for example @turf/area or `@turf/bearing'. Do we just not have example maps for these modules?

rpl had a few data types it could handle. If the result was a number, it would simply print the number in a div. Also worth noting that it would render any number of results, which was helpful for examples that had multiple inputs/outputs. One of the other really nice things about this approach is that the code was fully interactive and could be modified on the fly.

**Comment by rowanwins** [comment]
So I gave rpl a go but couldn't get it doing anything useful, probably user error on my part but I couldn't really make heads or tails of it.

Looking at the [jsdoc doco](http://usejsdoc.org/about-plugins.html) you can extend jsdoc with new tags so I don't feel too bad about my original proposal.

I'll put in a pull request showing what I've done so far and we can take it from there.

**Comment by DenisCarriere** [comment]
Thanks to @rowanwins, we've got a first prototype of having a map in TurfJS.

Using `@addToMap` in the JSDocs.

**Examples**

![image](https://cloud.githubusercontent.com/assets/550895/23840054/8364aac8-0778-11e7-8e9d-31133ab76986.png)

![image](https://cloud.githubusercontent.com/assets/550895/23840061/8f66bd20-0778-11e7-9e43-92672c4dec54.png)
