### ISSUE TITLE
add https:// in front of CDN url

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf-www#53]
This is kind of a damned-if-you-do-damned-if-you-dont problem.

If we add https:

* Then turf will work when people load files with file:// urls, like double-clicking HTML
* Turf will break on IE http pages
* Turf will break once you try to ajax anything, because file:// urls are abominations

If we don't:

* Turf won't work on file:// pages and it will appear broken to those who use them

**Comment by lyzidiamond** [comment]
This was a specific complaint from someone who did the turf exercise. I think there will be many situations with folks AJAXing geojson, so I advocate leaving as-is and adding more documentation/examples mentioning it explicitly.

**Comment by tmcw** [comment]
:+1: this will be a task for guides, not this url

**Comment by lyzidiamond** [comment]
Safe to close this?

**Comment by tmcw** [comment]
Yep!
