### ISSUE TITLE
AJAX examples

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf-www#55]
Connecting data to things is always a big area of confusion. We'll need to document this but also make it clear that it'll require libraries / works with many libraries / CORS / etc.

**Comment by lyzidiamond** [comment]
+100 :+1:

**Comment by tmcw** [comment]
Prepare for pwn, no amount of documentation will alleviate the problem of people copying the example but not the data it references :)

**Comment by tmcw** [comment]
Rethinking examples from the ground up.
