### ISSUE TITLE
Make editability of examples obvious

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf-www#56]
Probably something like a banner that says how to play with examples that goes away permanently once you x out of it?

**Comment by lyzidiamond** [comment]
Ah, yes! Bump here! Also paging @svmatthews who may have an idea of how to make this work.

**Comment by tchannel** [comment]
oh wow didn't even notice that before, awesome

**Comment by tmcw** [comment]
Rethinking examples from the ground up.
