### ISSUE TITLE
Download button on the website

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf-www#64]
discuss

**Comment by lyzidiamond** [comment]
Is there a significant cross-section of people who a) want to use the turf node module and b) don't feel comfortable doing it from the command line? If yes, then yes. If no, then no.

(Unless I'm misunderstanding the question in which case ignore me.)

**Comment by tmcw** [comment]
This is for people who want to download the javascript file to use it on a website without hotlinking our version, not for those who would be using node.

**Comment by lyzidiamond** [comment]
OH! Sorry.

Then yes, I think a download button would be radical.

**Comment by morganherlocker** [comment]
yeah agree :+1:
