### ISSUE TITLE
duplication between README.md and DOCUMENTATION.md

### ISSUE THREAD

**Issue by jfirebaugh** [Turfjs/turf-www#71]
DOCUMENTATION.md appears to be substantially a copy of material from README.md.

Is there a reason for the duplication or can we consolidate this so as not to get out of sync? I fixed a few things in DOCUMENTATION.md without realizing that it also was in README.md, and vice versa.

**Comment by morganherlocker** [comment]
Seems like site building info should exist here in the turf-www README.md, while module documentation info should exist in a DOCUMENTATION.md in Turfjs/turf. Ideally someone would be able to contribute a submodule to turf without having to know anything about the site, as long as they follow the jsdoc rules.

Thoughts @lyzidiamond ?

**Comment by lyzidiamond** [comment]
This slipped off my radar (my bad) but the goal was to move the README content to DOCUMENTATION.md (done) and then rewrite the README as an intro to Turf. I'll fix this.

**Comment by rowanwins** [comment]
I believe this is now resolved. DOCUMENTATION.md is now gone. The README.md only contains some basic info (although could do with a smidge of updating) and the CONTRIBUTING.md contains info on how to build the docs.
