### ISSUE TITLE
use templated type notation for Feature/FeatureCollection

### ISSUE THREAD

**Issue by jfirebaugh** [Turfjs/turf-www#72]
I suggest we use the [Closure Compiler convention](https://developers.google.com/closure/compiler/docs/js-for-compiler#generics) for generic / templated types when writing a type specifier for a GeoJSON `Feature` or `FeatureCollection` where the geometry or geometries have a specific geometry type.

* [For example](https://github.com/Turfjs/turf-point/compare/template)
* [More complicated example](https://github.com/Turfjs/turf-buffer/compare/template)

This will correct many types that are technically incorrect and make things explicit that are currently in prose or not documented at all.

**Comment by morganherlocker** [comment]
I like this. It definitely reflects the intent much more accurately. See any issues w/ this @tmcw?

**Comment by tmcw** [comment]
:+1: yep, looks great.

**Comment by mourner** [comment]
Nearly had a stroke after reading "I suggest we use the Closure Compiler...", glad it's only a convention :)

**Comment by lyzidiamond** [comment]
@tmcw @morganherlocker one of you going to do this, or should I run through and make it happen?

**Comment by lyzidiamond** [comment]
Gonna run through and do this now.

**Comment by lyzidiamond** [comment]
Doing a final check and this is lookin pretty weird:

![screen shot 2015-02-26 at 11 28 59 am](https://cloud.githubusercontent.com/assets/2523165/6399966/bef1ef70-bdaa-11e4-8b03-3844d9b73224.png)

@jfirebaugh and I already talked about how dox rewrites `Feature<Point>` to `Feature.<Point>` (which we should probably also change) but should we have some way for the UI to handle a situation like this, where the inputs have many options? Or am I the only one that's bothered by it?

**Comment by lyzidiamond** [comment]
Okay, scratch that, I don't mind it so much (in this case it actually looks fine)

![screen shot 2015-02-26 at 11 32 01 am](https://cloud.githubusercontent.com/assets/2523165/6400024/2447e7ee-bdab-11e4-877f-3138aee8aec6.png)

**Comment by jfirebaugh** [comment]
Modulo the periods, `turf.buffer` looks ok to me.

For things like `turf.centroid` which support a Feature or FeatureCollection of any geometry type, let's specify the type as `Feature | FeatureCollection` -- i.e., have the convention be that if the geometry type is _not_ specified, any geometry type is supported.

**Comment by lyzidiamond** [comment]
@jfirebaugh copy that!

**Comment by lyzidiamond** [comment]
This is done! Closing.
