### ISSUE TITLE
`units` type enum

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf-www#73]
Its tricky to keep all the docs up to date with the different units. I think we should create an [enum](http://en.wikipedia.org/wiki/Enumerated_type) type that we can link to, which provides an up to date list of valid values. Then as long as turf-destination, and turf-distance support these, all the other modules that depend on them will be kept up to date.

Thoughts @lyzidiamond ?

**Comment by lyzidiamond** [comment]
That's a great idea! It will also address one of the main blockers folks have with using some of these functions. In particular, if we can define some of the units for grids (cell-size, resolution, etc) it would be a slam dunk.

**Comment by DenisCarriere** [comment]
Since the `turf-www` has automated tests now, I believe this is no longer needed. If there's a Javascript error in the JSDocs it would get caught with `npm run test-runner` / `npm test`.

```bash
$ npm run test-runner

> turf-www@1.0.0 test-runner /Users/mac/Github/turf-www-main
> ava test/turf.js


  72 passed
```
