### ISSUE TITLE
turf.buffer example error

### ISSUE THREAD

**Issue by camilleanne** [Turfjs/turf-www#77]
The repl is giving an error for the example code for turf.buffer:

![screen shot 2015-03-30 at 1 21 02 pm](https://cloud.githubusercontent.com/assets/3952537/6905852/b639fc44-d6df-11e4-8e63-e5befa5142c2.png)

**Comment by morganherlocker** [comment]
Thanks, this is fixed now http://turfjs.org/static/docs/module-turf_buffer.html

![](https://dl.dropbox.com/s/klv4xpemgxm0qrb/Screenshot%202015-03-30%2017.08.04.png?dl=0)
