### ISSUE TITLE
Switch to documentation

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf-www#78]
https://github.com/documentationjs/documentation is very close to showtime. when it is, we should switch.

**Comment by lyzidiamond** [comment]
I'd love to run point on this so I can learn more about documentationjs, if you wanna work on it together @tmcw.

**Comment by tmcw** [comment]
:+1: definitely! @lyzidiamond ping me whenever you have time this week, there's one small tweak necessary to documentationjs but I can make it pretty quickly & easily.

**Comment by tmcw** [comment]
Merging into https://github.com/Turfjs/turf/issues/316
