### ISSUE TITLE
"learn" heading on homepage

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf-www#79]
* link to stackoverflow tag http://stackoverflow.com/questions/tagged/turfjs
* link to chat room?
* link to github issues
* link to existing guides
* link to workshopper

/cc @tchannel @morganherlocker @lyzidiamond

**Comment by morganherlocker** [comment]
Leaning towards workshopper or a (not yet existing) rpl-www based tutorial similar to [codecademy](http://www.codecademy.com/). We might want to link to the chatroom as well. Stackoverflow and GH are probably a bit too uncurated to be helpful to someone getting started. Guides could be good, but the current guides are really more focused on integrating with Leaflet/Mapbox.js than learning Turf more broadly (though we could change this by creating more guides).

**Comment by lyzidiamond** [comment]
I'd be into making more guides! I am definitely thinking about shifting focus to Turf in the coming weeks, so I can put some serious time into that.

To add:

- Dear Morgan / Recipes
- Turf blog posts

Also:

- Change UI on docs to make it clear that mini rpls are editable

**Comment by tmcw** [comment]
We don't have very good places to link to, so no block for now.
