### ISSUE TITLE
v3 update

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf-www#81]
When this is published, we will regen the docs. https://github.com/Turfjs/turf/pull/256

**Comment by lyzidiamond** [comment]
We also need to manually change the CDN link on the front page.

**Comment by morganherlocker** [comment]
@lyzidiamond yep, here's my todo list https://gist.github.com/morganherlocker/65f65cf184f917a04f33

**Comment by rowanwins** [comment]
Think this can be considered done
