### ISSUE TITLE
turf.difference

### ISSUE THREAD

**Issue by mcwhittemore** [Turfjs/turf-www#84]
I'm a bit confused about how this is happening, but turf.difference is making it into the docs but not into the module.

![image](https://cloud.githubusercontent.com/assets/1551510/10008794/76e9dd1a-60a1-11e5-8ba4-34a0b9a01d4d.png)

http://turfjs.org/static/docs/module-turf_difference.html

![image](https://cloud.githubusercontent.com/assets/1551510/10008789/6262477e-60a1-11e5-9c63-4cbb1b2e9783.png)

**Comment by lyzidiamond** [comment]
I did a docs redeploy here but it didn't help. Not sure how to fix -- @morganherlocker or @tmcw?

**Comment by mcwhittemore** [comment]
@lyzidiamond can you check your node_modules for turf-difference? I think it might just still be in the node_modules folder even though its not in package.json.

**Comment by lyzidiamond** [comment]
@mcwhittemore it's not there... it's not in the list of modules the turf runner is grabbing, I think.

**Comment by tcql** [comment]
If this is pulling from Turfjs/turf#master, the module is listed as `turf-erase`. We renamed some time ago and I believe docs got updated, but haven't rolled a new release of Turf with the rename.

**Comment by tcql** [comment]
Just tested, editing the rpl on the turf-difference doc and changing `turf.difference` to `turf.erase` makes it work. The fix for this would be for us to roll a release with the rename completed.

**Comment by tmcw** [comment]
Documentation now updated, matches code.
