### ISSUE TITLE
Redoing turf docs

### ISSUE THREAD

**Issue by rowanwins** [Turfjs/turf-www#91]
Gday @morganherlocker  & @DenisCarriere 

I'm currently having a play with redoing the docs for Turf so I just thought I'd give you a heads up and an opportunity for input. 

Below is a screen grab of my early work which gives you an idea of my vague plan, nothing revolutionary but hopefully a bit cleaner.
![alt tag](https://www.dropbox.com/s/hmla5nwdyfi61nm/sample.jpeg?dl=1)

I'm also thinking through how I might go about re-introducing the map examples (rather than just the sample code) but I suspect this will happen down the track if I can think of a good way to do it...

Anyway if you have any other ideas let me know

Cheers
Rowan

PS It's all still using the documentation.js stuff

**Comment by DenisCarriere** [comment]
@rowanwins Looks good to me! I would love to see map elements as examples, it would be a great visual explanation of what the function/module is suppose to do.
👍

**Comment by rowanwins** [comment]
Changes now merged!

**Comment by morganherlocker** [comment]
Thanks @rowanwins! Looks great, fantastic work!
