### ISSUE TITLE
Search Header URL mismatched

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf-www#99]
Tried to click the main headers in the search and the page doesn't seem to recognize the Header URL.

![image](https://cloud.githubusercontent.com/assets/550895/23372595/3318c4de-fcea-11e6-983d-71f909af0497.png)

Currently URL points to
```
http://turfjs.org/docs/#meta
```

Should be
```
http://turfjs.org/docs/#Meta
```

**Comment by rowanwins** [comment]
good spotting @DenisCarriere , I can tackle this if you'd like

**Comment by DenisCarriere** [comment]
Sounds good :)
